### ISSUE TITLE
Implement Majors Functionality

### ISSUE THREAD

**Issue by cmarq07** [cmarq07/exploreUW-app#7]
# Majors
This page's final functionality should be able to...
- Display a list of all (or at least most) of the majors within UW
  - Also show the shortcode for what type of major it is
    - **CC** - Capacity Constrained _(Competitive - not guaranteed admission)_
    - **MR** - Minimum Requirement _(Guaranteed admission if certain requirements/classes are met)_
    - **OM** - Open Major _(Available to all)_
- Display a list of prerequisites for each major
- (IF APPLICABLE) Display a list of tips/advice for majors (most likely Capacity Constrained (CC) or Minimum Requirement (MR) majors

## TODO Items (Checklist)
- [x] Showcase all/most majors within UW and the shortcodes of each
- [x] Display prerequisites for each major
  - [ ] **OPTIONAL** - On click, open an expanded page that shows even more details
- [x]  Display tips/advice for all displayed majors
- [ ] Make the list of items dynamic to the MongoDB database
