### ISSUE TITLE
Implement RSOs Functionality

### ISSUE THREAD

**Issue by cmarq07** [cmarq07/exploreUW-app#8]
# RSOs
**RSO** - Registered Student Organization
This page's final functionality should be able to...
- Display a list of all / many RSOs within UW
  - Display some details about each RSO like:
    - Meeting Times / Days
    - Location (if applicable)
    - Appx. number of members
    - Any requirements / specific populations
- Be able to filter this list of RSOs based on some generic filter requirements (e.g., dance, gaming, social, academic, etc.)

## TODO Items (Checklist)
- [ ] Display a list of RSOs within UW with details about each (reference above)
- [ ] Have a filter system for RSOs
- [ ] Make this list dynamic by using the MongoDB database
- [ ] Allow SAO advisors to add new RSOs if they are authenticated inside the app
