### ISSUE TITLE
Implement Events Functionality

### ISSUE THREAD

**Issue by cmarq07** [cmarq07/exploreUW-app#9]
# Events
This page's final functionality should be able to...
- Display a list of upcoming and past events at UW
- Display some small details about the events like where / when it is occurring
- EVENTUALLY, an optional user story allows for students to post new events
  - Another one is to have notifications when a new event is posted / upcoming (e.g., a user "subscribes" to an event and receives updates about it)

## TODO Items (Checklist)
- [x] Display a list of upcoming and past events at UW along with details about them (see above)
- [ ] Make this list dynamic by using the MongoDB database
- [ ] **OPTIONAL USER STORY** - Receive notifications when a new event is posted OR when an event that a user is "subscribed" to receives updates, such as being canceled, rescheduled, or is upcoming (e.g., in 3 Days or in 1 Hour)
- [ ] **OPTIONAL USER STORY** - Allow users to post new events
